import Head from 'next/head';
import React, { useEffect } from 'react'; 
import { getTracks } from "../lib/firebase";
import Header from '@/components/header';
import SearchTrackBox from '@/components/search-track-box';
import TrackList from '@/components/track-list';


export default function Home() { 
  const [tracks, setTracks] = React.useState([]);
  const [playTrack, setPlayTrack] = React.useState(null);
 
  const listTracks = React.useCallback(async () => {
    let data = await getTracks();
    setTracks(data);
  }, []);

  useEffect(() => { listTracks(); }, [listTracks]);

  return (
    <>
      <Head>
        <title>LedMusic</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='h-screen'>
        <div className='max-w-lg m-auto mt-20 relative'>
          <Header />
          <SearchTrackBox {...{ listTracks, playTrack, setPlayTrack }} />
          <TrackList {...{ tracks, listTracks, playTrack, setPlayTrack }} />
        </div>
      </main>
    </>
  )
}
